# Generated by Django 5.2.1 on 2025-05-09 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='image',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='position',
            name='title',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='has_voted',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='voter_id',
        ),
        migrations.AddField(
            model_name='candidate',
            name='blockchain_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='blockchain_sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='position',
            name='blockchain_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='blockchain_sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='position',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='blockchain_sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='ethereum_address',
            field=models.CharField(default='', max_length=42, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_votes', to='voting_main.candidate'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting_main.voter'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'candidate')},
        ),
    ]
